---
title: "Project 3"
author: "Sung Lee"
date: "3/18/2020"
output: 
  html_document: 
    df_print: paged
---

References:
[http://www.sthda.com/english/wiki/text-mining-and-word-cloud-fundamentals-in-r-5-simple-steps-you-should-know]
[https://www.tidytextmining.com/nasa.html#word-co-ocurrences-and-correlations]
```{r}
library(tm)
library(SnowballC)
library(wordcloud)
library(RColorBrewer)
library(stringr)

library(tokenizers)


jobs <- read.csv('data_scientist_united_states_job_postings_jobspikr.csv')

head(jobs)


# Remove non-ascii characters
jobs$job_description <-  gsub("[^\x20-\x7E]", "", jobs$job_description)



descriptions <- Corpus(VectorSource(jobs$job_description))




toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " ", x))
descriptions <- tm_map(descriptions, toSpace, "/")
descriptions <- tm_map(descriptions, toSpace, "\n")
descriptions <- tm_map(descriptions, toSpace, "@")
descriptions <- tm_map(descriptions, toSpace, "\\|")


descriptions <- tm_map(descriptions, content_transformer(tolower))
descriptions <- tm_map(descriptions, removeWords, stopwords("english"))
descriptions <- tm_map(descriptions, removePunctuation)
descriptions <- tm_map(descriptions, stripWhitespace)

#Stem the document: reduces common word endings (ing, es, s)
#descriptions <- tm_map(descriptions, stemDocument)


dtm <- TermDocumentMatrix(descriptions)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)

```

### This is how the frequency looks
```{r}
d
```


```{r}
#Set ups the Word Cloud
set.seed(1234)
wordcloud(words = d$word, freq = d$freq, min.freq = 100,
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))

```